# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2022 Oplus. All rights reserved.




#ifdef CONFIG_OPLUS_FEATURE_FAULT_INJECT_CHG
obj-$(CONFIG_OPLUS_FEATURE_FAULT_INJECT_CHG) += charger/
#endif
