SMEM_MAILBOX_DLKM_BOARD_PLATFORMS_LIST := sun
SMEM_MAILBOX_DLKM_BOARD_PLATFORMS_LIST += canoe
SMEM_MAILBOX_DLKM_BOARD_PLATFORMS_LIST += hamoa
SMEM_MAILBOX_DLKM_BOARD_PLATFORMS_LIST += chora
SMEM_MAILBOX_DLKM_BOARD_PLATFORMS_LIST += malabar
ifneq (,$(call is-board-platform-in-list2,$(SMEM_MAILBOX_DLKM_BOARD_PLATFORMS_LIST)))
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/smem-mailbox.ko
endif
