# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

export CONFIG_MSM_TOUCH=m
export CONFIG_TOUCHSCREEN_GT9XX=y
export CONFIG_TOUCHSCREEN_GT9XX_UPDATE=y
export CONFIG_TOUCHSCREEN_GT9XX_DEBUG=y
export CONFIG_QTS_ENABLE=y
