TARGET_DATARMNET_ENABLE := false

ifeq ($(TARGET_KERNEL_DLKM_DISABLE), true)
	ifeq ($(TARGET_KERNEL_DLKM_DATARMNET_OVERRIDE), true)
		TARGET_DATARMNET_ENABLE := true
	endif
else
	TARGET_DATARMNET_ENABLE := true
endif

ifeq ($(TARGET_DATARMNET_ENABLE), true)
	#Build rmnet core
	DATA_DLKM_BOARD_PLATFORMS_LIST := sun
	DATA_DLKM_BOARD_PLATFORMS_LIST += canoe
	DATA_DLKM_BOARD_PLATFORMS_LIST += vienna
	DATA_DLKM_BOARD_PLATFORMS_LIST += monaco
        DATA_DLKM_BOARD_PLATFORMS_LIST += lahaina
	DATA_DLKM_BOARD_PLATFORMS_LIST += bengal
	DATA_DLKM_BOARD_PLATFORMS_LIST += chora
	DATA_DLKM_BOARD_PLATFORMS_LIST += malabar
	DATA_DLKM_BOARD_PLATFORMS_LIST += shikra

	RMNET_CTL_DLKM_PLATFORMS_LIST := sun
	RMNET_CTL_DLKM_PLATFORMS_LIST += canoe
	RMNET_CTL_DLKM_PLATFORMS_LIST += vienna
	RMNET_CTL_DLKM_PLATFORMS_LIST += monaco
	RMNET_CTL_DLKM_PLATFORMS_LIST += lahaina
	RMNET_CTL_DLKM_PLATFORMS_LIST += bengal
	RMNET_CTL_DLKM_PLATFORMS_LIST += chora
	RMNET_CTL_DLKM_PLATFORMS_LIST += malabar

	ifneq ($(TARGET_BOARD_AUTO),true)
		ifneq (,$(call is-board-platform-in-list2,$(DATA_DLKM_BOARD_PLATFORMS_LIST)))
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_core.ko
		endif
		ifneq (,$(call is-board-platform-in-list2,$(RMNET_CTL_DLKM_PLATFORMS_LIST)))
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_ctl.ko
		endif
	endif
endif
